version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t phoenix-app .
      - docker tag phoenix-app:latest $ECR_URL:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_URL:latest
      - echo Generating imagedefinitions.json...
      - echo '[{"name":"phoenix-container","imageUri":"'$ECR_URL:latest'"}]' > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
